 const ActionTypes = {
    GENRE_LOADING: 'GENRE_LOADING',
    GENRE_SUCCESS: 'GENRE_SUCCESS',
    GENRE_ERROR: 'GENRE_ERROR',

    FAV_LOADING: 'FAV_LOADING',
    FAV_ERROR: 'FAV_ERROR',
    FAV_SUCCESS: 'FAV_SUCCESS',

    ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
    REMOVE_FAVORITE: 'REMOVE_FAVORITE',

}

export default ActionTypes;